/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CharactersRouteImport } from './routes/characters'
import { Route as CharacterinfoRouteImport } from './routes/characterinfo'
import { Route as IndexRouteImport } from './routes/index'

const CharactersRoute = CharactersRouteImport.update({
  id: '/characters',
  path: '/characters',
  getParentRoute: () => rootRouteImport,
} as any)
const CharacterinfoRoute = CharacterinfoRouteImport.update({
  id: '/characterinfo',
  path: '/characterinfo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/characterinfo': typeof CharacterinfoRoute
  '/characters': typeof CharactersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/characterinfo': typeof CharacterinfoRoute
  '/characters': typeof CharactersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/characterinfo': typeof CharacterinfoRoute
  '/characters': typeof CharactersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/characterinfo' | '/characters'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/characterinfo' | '/characters'
  id: '__root__' | '/' | '/characterinfo' | '/characters'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CharacterinfoRoute: typeof CharacterinfoRoute
  CharactersRoute: typeof CharactersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/characters': {
      id: '/characters'
      path: '/characters'
      fullPath: '/characters'
      preLoaderRoute: typeof CharactersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characterinfo': {
      id: '/characterinfo'
      path: '/characterinfo'
      fullPath: '/characterinfo'
      preLoaderRoute: typeof CharacterinfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CharacterinfoRoute: CharacterinfoRoute,
  CharactersRoute: CharactersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
